# Generated by Django 4.2.11 on 2025-03-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add a new book'), ('can_change_book', 'Can edit book details'), ('can_delete_book', 'Can delete a book')]},
        ),
    ]
