# Generated by Django 4.2.11 on 2025-03-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add book'), ('can_change_book', 'Can edit book'), ('can_delete_book', 'Can delete book')]},
        ),
    ]
